## 예외처리
프로그램은 오류가 발생하면 에러를 출력하며 강제 종료되거나, 원하지 않는 동작을 한다.

발생하는 오류를 안전하게 처리하고, 강제 종료 되지않게 한 다음 오류 발생 후 처리할 루틴을 실행하고자 할 때 예외처리를 사용한다

* 기본적인 형태

	```python
	try:
		시도할 코드
	except:
		에러가 발생했을 경우 실행할 코드
	```

* 여러가지 오류를 구분할 경우

	```python
	try:
		시도할 코드
	except <예외 클래스1>:
		에러클래스 1에 해당할 경우 실행할 코드
	except <예외 클래스2>:
		에러클래스 2에 해당할 경우 실행할 코드
	except <예외 클래스1>:
		에러클래스 3에 해당할 경우 실행할 코드
		...
	```
	
* 예외상황을 변수로 사용할 경우

	```python
	try:
		시도할 코드
	except <예외클래스> as <변수명>:
		<변수명>을 사용한 코드
	```
	
#### try~else

`else`문은 `try` 이후 예외가 발생하지 않을 경우 실행된다.

```python
try:
	시도할 코드
except:
	에러가 발생했을 경우 실행할 코드
else:
	에러가 발생하지 않았을 시 실행할 코드
```

#### 예외 발생시키기

예외를 발생시킬 때는 raise 구문을 사용한다.

```python
raise IndexError
```

#### 예외 만들기

내장 클래스 `Exception`을 상속받아 커스텀 예외를 만들 수 있다.

초기화 메서드에서 예외 처리할 데이터를 받고, `print`문으로 사용되고 싶다면, `__str__` 메서드를 오버라이드 해준다.

```python
class 예외이름(Exception)
	def __str__(self):
		return '출력할 메시지'
```
